version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    ports:
      - "9091:5432"
#      - "6541:5432"
#    hostname: stats-db
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
